### ISSUE TITLE
Better detailed and explained usage example please?

### ISSUE THREAD

**Issue by ElektroStudios** [Nekmo/telegram-upload#102]
I don't understand how to use it. 

Why the example "**$ telegram-upload file1.mp4 /path/to/file2.mkv**" takes two paths?. it should not take just one path (the local file you want to upload) and a second parameter a channel id or something where to send the file?.

I just want to automate the publication of new messages in my (private) channel, to send a image / cover of a movie (in photo mode, a big image), and publish the movie files below that, all in a specific channel (I have various). How can I use this program for my purpose?.

**Comment by Nekmo** [comment]
telegram-upload supports uploading one or multiple files. You can check the documentation:

https://docs.nekmo.org/telegram-upload/usage.html

**Comment by ElektroStudios** [comment]
Many thanks
