### ISSUE TITLE
--album parameter is missing

### ISSUE THREAD

**Issue by ElektroStudios** [Nekmo/telegram-upload#103]
I'm trying to upload a directory that contains 2 jpeg files and some rar files, I would like to "join" all files to be posted in the same telegram message, just like If I open **Telegram Deskop** and I drag and drop all the files there, it will create only 1 message / album. So I tried to use the **--album** parameter like this:

`telegram-upload.exe  --album --directories "recursive" --to "%inviteLink%" "%sourceDir%"`

But it throws this error:

> Error: no such option: --album

(and same respective error message happens for its short name: **-a**)

The parameter is specified in the docs: https://docs.nekmo.org/telegram-upload/usage.html, but it is missing when using the **--help** command. 

Is this functionality deleted from the script?. It would be added again in the future?.

**Comment by Nekmo** [comment]
This feature is available in the development version. You can see the issue here: https://github.com/Nekmo/telegram-upload/issues/61

To install from the development version:
```
$ pip install https://github.com/Nekmo/telegram-upload/archive/master.zip
```

More installation options:
https://docs.nekmo.org/telegram-upload/installation.html

**Comment by ElektroStudios** [comment]
Thanks again for support!

**Comment by sideloading** [comment]
FYI if you already have telegram-upload installed with pip, you need to specify the --upgrade flag

```
$ pip install https://github.com/Nekmo/telegram-upload/archive/master.zip --upgrade
```

Hope it helps, was looking for the --album feature.
