### ISSUE TITLE
Post various files in a single message instead of sending one message per file uploaded.

### ISSUE THREAD

**Issue by ElektroStudios** [Nekmo/telegram-upload#104]
I'm using the latest development version from the master branch. 

My question is how can I post various files in a single message instead of sending one message per file uploaded?.

So if I have a directory with three rar files inside, and using telegram-upload.exe with this syntax (VB.NET):

`telegram-upload.exe --caption "{caption}" --directories "recursive" --to "{InviteLink}" "{sourceDir}"`

It sends three messages:
![](https://i.imgur.com/ES1aTU3.png)

But I would like to send only one message containing all the files, like this example:
![](https://i.imgur.com/GsvTc99.png)

PS: I thought that maybe using the **--album** parameter would solve this, but it does not support rar files, and image files uploaded using the **--album** parameter are not represented in the same way as if I drag & drop a bunch of images or files in the Telegram desktop UI.

**Comment by Nekmo** [comment]
Hi @ElektroStudios,

I don't know what feature in Telegram is this. I need to investigate it but I'm interest in implement it in a future release.

Thanks!

**Comment by Nekmo** [comment]
Hi @ElektroStudios,

I don't know what feature in Telegram is this. I need to investigate it but I'm interest in implement it in a future release.

Thanks!

**Comment by Nekmo** [comment]
Resolved using `--album`.

**Comment by ElektroStudios** [comment]
Thanks, it's time to try it!
