### ISSUE TITLE
Markdown 

### ISSUE THREAD

**Issue by DougRzz** [Nekmo/telegram-upload#107]
Hi. Thanks for the v. useful python package.
I would like to colour or add hyperlinks to the uploaded message text. To do this, perhaps enabling Markdown would do the trick. Is this possible?

**Comment by Nekmo** [comment]
Hi there is nothing similar in the telegram message format:

https://core.telegram.org/api/entities

Regards

**Comment by DougRzz** [comment]
No. There is no way to create hyperlinked text in the message entities.  

For example:
[Youtubelink](https://www.youtube.com/watch?v=PCwL3-hkKrg)
