### ISSUE TITLE
Question - Is there a way/fork to allow uploading everything there is inside a folder?

### ISSUE THREAD

**Issue by AlexRabbit** [Nekmo/telegram-upload#109]
Everything works flawlessly however is kinda tedious to upload file by file. 
My objective is to make a folder that sync in multiple devices just like dropbox.

**Comment by AlexRabbit** [comment]
Bonus points for having a log file to avoid uploading repeated media and only upload the media that is not already uploaded.

**Comment by Nekmo** [comment]
> Everything works flawlessly however is kinda tedious to upload file by file.
> My objective is to make a folder that sync in multiple devices just like dropbox.

You can upload everything from a directory, but today there is nothing similar to synchronization.

**Comment by f95180** [comment]
> > Everything works flawlessly however is kinda tedious to upload file by file.
> > My objective is to make a folder that sync in multiple devices just like dropbox.
> 
> You can upload everything from a directory, but today there is nothing similar to synchronization.

How can upload everything from a directory?

**Comment by Nekmo** [comment]
> > > Everything works flawlessly however is kinda tedious to upload file by file.
> > > My objective is to make a folder that sync in multiple devices just like dropbox.
> > 
> > 
> > You can upload everything from a directory, but today there is nothing similar to synchronization.
> 
> How can upload everything from a directory?

https://docs.nekmo.org/telegram-upload/usage.html#cmdoption-telegram-upload-directories
