### ISSUE TITLE
Telegram is having internal issues TimeoutError: A timeout occurred while fetching data from the worker (caused by GetFileRequest)

### ISSUE THREAD

**Issue by SK-sep** [Nekmo/telegram-upload#112]
* telegram-upload version: 0.4.0
* Python version: 3.9
* Operating System: MacOS BigSur 11.2.3
* Dependencies list (run `pip freeze`):

cffi==1.14.5
click==7.1.2
cryptg==0.2.post0
hachoir==3.1.2
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.20
rsa==4.7.2
telegram-upload==0.4.0
Telethon==1.21.1

### Description

Downloading "x.ipa"  [#########---------------------------]   25%  00:17:01Telegram is having internal issues TimeoutError: A timeout occurred while fetching data from the worker (caused by GetFileRequest)
Downloading "x.ipa"  [#############-----------------------]   37%  00:15:27Telegram is having internal issues TimeoutError: A timeout occurred while fetching data from the worker (caused by GetFileRequest)

### What I Did

I run the command for dowloading file from telegram "telegram-download -f $link -d" and when downloading, showing up this error

**Comment by Nekmo** [comment]
It looks like a temporary network error. Has it worked afterwards?
