### ISSUE TITLE
Numbered files are uploaded in weird order

### ISSUE THREAD

**Issue by tissole** [Nekmo/telegram-upload#113]
Hello and thank you for developing this app. My config:
 * telegram-upload version: 0.4.0
* Python version: 3.9.2
* Operating System: Windows 10
* Dependencies list (run `pip freeze`):
cffi==1.14.5
click==7.1.2
cryptg==0.2.post4
hachoir==3.1.2
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.20
rsa==4.7.2
telegram-upload==0.4.0
Telethon==1.21.1

### Description

When files are numbered 1, 2, 3...10, 11, 12, etc, the app uploads them in a weird manner 1, 10, 11, 12...2, 3, 4, etc

### What I Did

telegram-upload --directories recursive -a 'D:\Docs'

 I wish that the files are uploaded like this: 1, 2, 3, 4... 10, 11, 12, etc

**Comment by Nekmo** [comment]
It will be added in a future version (the files will be sorted alphabetically). Thanks!

**Comment by tissole** [comment]
Great! Thank you!

**Comment by ElektroStudios** [comment]
> 
> 
> It will be added in a future version (the files will be sorted alphabetically). Thanks!

You would mean the files will be sorted by Natural Sort (Windows Explorer sort). Not alphabetically.

**Comment by tissole** [comment]
@ElektroStudios Yes, this is what I want, but I didn't know the correct name for this feature, Thank you for the info!

**Comment by Nekmo** [comment]
Fixed in v0.6.0. Use the `--sort` parameter. The **natsort** Python package must be installed for natural ordering. 

```
pip install natsort
```
