### ISSUE TITLE
Feature request- Increasing upload speed by implementing parallel file transfers

### ISSUE THREAD

**Issue by tissole** [Nekmo/telegram-upload#116]
There is a project that discusses this
https://gist.github.com/painor/7e74de80ae0c819d3e9abcf9989a8dd6

The current speed is pretty low so it could improve from such an enhancement.

Update. There are 2 other projects that have an option to increase the upload speed significantly.
[Kotatogram](https://github.com/kotatogram/kotatogram-desktop) and [64Gram](https://github.com/TDesktop-x64/tdesktop). The feature is called upload speed boost and when is enabled the speed increases 10X compared to that of the official client, (100 Mb/s vs. 10 Mb/s).

Maybe this information is helpful for developing a similar feature.

**Comment by Nekmo** [comment]
This incident is duplicated by #64. But the issue may be interesting to research it, thanks!

**Comment by tissole** [comment]
Thank you for looking into this. This feature is badly needed because the speed is very low right now. Takes a very long time to upload things. I have read issue #64 and I understand your concern, the safety of users' accounts must come first. But I think there is a smart way to doing this. Currently, the developer already implemented a workaround to deal with flood errors.

If the script obeys Telegram limits and does not trigger flood waits the user's accounts are safe.

**Comment by Nekmo** [comment]
Speed improvements have been implemented in Telegram-upload v0.7.0. You can see the benchmarks with the improvement in:
https://docs.nekmo.org/telegram-upload/upload_benchmark.html
