### ISSUE TITLE
Feature Request - Choose channel by ID

### ISSUE THREAD

**Issue by tissole** [Nekmo/telegram-upload#118]
Now uploading to a private channel is possible only by indicating the invite link, is not working with channel ID. But this method triggers some wait messages from TG after some time and the script stops.

Please add an option to use channels IDs

**Comment by Nekmo** [comment]
It will be investigated. Can you put an example id?

**Comment by tissole** [comment]
This is a channel ID. 

![Channel ID](https://user-images.githubusercontent.com/78413495/120634825-5f5b4700-c474-11eb-8c6f-d025fc0be586.png)

Many unofficial Telegram clients show channel and group IDs when a user clicks on the channel name. There are also numerous bots that show this info, like @userinfobot for example. The error I got is similar to that posted on #[111](https://github.com/Nekmo/telegram-upload/issues/111#issue-860455736). Channel usernames can be used only for public channels and groups, but private channels and groups don't have usernames and the only option is to use their IDs.

Using channel invite triggers flood errors because Telegram confuses files uploaded with users added to a channel/group. I made my channel public and I used the username and the error was not encountered anymore.

**Comment by muyangren907** [comment]
@tissole Maybe this can help you
https://github.com/muyangren907/telegram-upload
@Nekmo Because I am not very familiar with GitHub operation, I can only fork a copy and submit it in my own warehouse

**Comment by tissole** [comment]
@muyangren907 Thanks a lot! I tested and is working! No more flood messages :)

**Comment by Nekmo** [comment]
Fixed in telegram-upload v0.6.0.
