### ISSUE TITLE
Is it possible to send text message only?

### ISSUE THREAD

**Issue by eriksonssilva** [Nekmo/telegram-upload#127]
* telegram-upload version: 0.4.0
* Python version: 3.9.6
* Operating System: Windows 10
* Dependencies list (run `pip freeze`):

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
Everything works smoothly, except for the fact I cannot figure out if there's a way of sending a text message only.
I have tried sending something using telegram-upload --caption "blabla" --to "https://t.me/joinchat/somethingHere".
But nothing happens, no error, no nothing.
However, if I upload a file, it will be uploaded and the caption "blabla" will be added...
Is it possible to send a text only?
Thanks in advance!

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Nekmo** [comment]
It is normal, Telegram-upload is created to upload and download files. Can you describe what you need?

**Comment by eriksonssilva** [comment]
Thanks a lot for the quick answer!

Well, I am writing a powershell script that will upload files, but before this, it'd send a message with a brief description.
E.g.:
Music Course Part 1 to 9
Timestamp: xxxx

something like that.

And then the telegram-upload would start uploading the files right after that.

That's basically it.

Thanks!
