### ISSUE TITLE
Bug in audio files tagging

### ISSUE THREAD

**Issue by tissole** [Nekmo/telegram-upload#133]
I'm on Windows 10 running version 0.4 of the script. Pip freeze

cffi==1.14.6
click==8.0.1
colorama==0.4.4
cryptg==0.2.post4
hachoir==3.1.2
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.20
rsa==4.7.2
telegram-upload==0.4.0
Telethon==1.23.0

I uploaded an audiobook and the tags were set incorrectly. The first file has the tags from the second file, the second has the tags from the third, and so on. In the files, tags are set correctly. I also used a bot that has put the tags correctly. But that bot was using Mutagen library for tagging. So maybe is a problem with hachoir. Can you add Mutagen support for tagging?

**Comment by Nekmo** [comment]
Probably related to this issue: https://github.com/Nekmo/telegram-upload/issues/101

**Comment by tissole** [comment]
I will close this issue because it is not related to your script. I discovered that the audio files with issues have 2 sets of tags, ID3v1 and ID3v2. The old tags have the name of the file set incorrectly, and the newer tags have the name set correctly. The Telegram Desktop reads the newer tags, this is why the filenames appear correctly, but your script uses hachoir who apparently prefers the old tags, ID3v1, which have incorrect file names.
