### ISSUE TITLE
Parameter -a (albúm)

### ISSUE THREAD

**Issue by Nideapum** [Nekmo/telegram-upload#134]
* telegram-upload version: 0.4.0
* Python version: 3.7
* Operating System: Raspbian OS
* Dependencies list (run `pip freeze`): telegram-upload==0.4.0

### Description
The -a parameter is not working.

### What I Did
$ `telegram-upload -a`
```
Usage: telegram-upload [OPTIONS] [FILES]...
Try 'telegram-upload --help' for help.

Error: no such option: -a
```

**Comment by zabeiua** [comment]
There is no -a in telegram-upload --help

**Comment by tissole** [comment]
Check  #103

**Comment by Nideapum** [comment]
Thanks!
