### ISSUE TITLE
Stream files ??

### ISSUE THREAD

**Issue by sadequzv710** [Nekmo/telegram-upload#137]
Hello.thanks for amazing bot.

is it possible to add this feature :
instead of uploading files to channel or group, use the stream in channel or group that we are admin ?

thanks.

**Comment by Nekmo** [comment]
Sorry, I don't quite understand your question. 

If you want to stream an incomplete file on your computer you have this issue: https://github.com/Nekmo/telegram-upload/issues/47

If you want your videos to be streamed, you have this other issue: https://github.com/Nekmo/telegram-upload/issues/59

**Comment by Nekmo** [comment]
Closed due to inactivity.
