### ISSUE TITLE
Alternate installation way

### ISSUE THREAD

**Issue by cyberboysumanjay** [Nekmo/telegram-upload#14]
* telegram-upload version: 0.1.6
* Python version: 3.6
* Operating System: Pop-OS

### Description
I was trying to use this in one of my Flask Projects. I deployed the website on Heroku so I can't enter API ID and HASH in the terminal. I was interested to know whether I can pass the ID and Hash along with the telegram-upload command? Or is there a way to set up the config in another way? 

A manual installation way will be helpful.

### What I Did
Tried Heroku console but no luck.

**Comment by Nekmo** [comment]
Configuration is stored in `~/.config/telegram-upload.json`:

```
{"api_id": 22xxxx, "api_hash": "fc587456e4c4a4ffdaaa9xxxxxxxxxxxx"}
```

**Comment by Nekmo** [comment]
Added to README.rst:

Credentials are saved in ``~/.config/telegram-upload.json`` and ``telegram-upload.session`` (in the current
directory). You must make sure that these files are secured. You can copy these files to authenticate
``telegram-upload`` on more machines, but it is advisable to create a session file for each machine.
