### ISSUE TITLE
private chat link has changed format, how to make it work when uploading to private upload? 

### ISSUE THREAD

**Issue by rsyqvthv** [Nekmo/telegram-upload#145]
* telegram-upload version: 0.4
* Python version:3.8
* Operating System:windows 10
* Dependencies list (run `pip freeze`):

### Description

private chat link used to be: `https://telegram.me/joinchat/B-UUVD8-WVj8KtZysJzIiw`
but now it changed like: `https://t.me/+w2q1rEjpyoCmOWM8`

thus when I use the newer link as argument for `--to` to uploading to a private chat, telegram-upload returns:

`Cannot find any entity`

### What I Did

I've tried: 

`https://t.me/+w2q1rEjpyoCmOWM8`
`w2q1rEjpyoCmOWM8`

also tried make up telegram id like: 

`1650026146` 10 digitals
`+10001650026146` plus +1000

they all came back same error: `Cannot find any entity`

and I found out https://github.com/Nekmo/telegram-upload/issues/144#issuecomment-1008005654 in this forum, but I am not quite understand where should the fix code goes to

### ask for solution

any workaround that I can upload to a private chat without change it to public?

**Comment by tulkarxxx** [comment]
I have the same issue....

**Comment by Nekmo** [comment]
This will be added in the next release, thanks!

**Comment by rsyqvthv** [comment]
thank you!!! :)

**Comment by joan-carles** [comment]
I know this seems closed but I have all the python packages updated and using the latest version and the problem persists for me.

```
pi@raspberrypi:~ $ pip freeze
asn1crypto==1.5.1
attrs==21.4.0
bcrypt==3.2.0
beautifulsoup4==4.11.1
cached-property==1.5.2
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.12
click==8.1.2
cryptg==0.2.post4
cryptography==36.0.2
distro==1.7.0
docker==5.0.3
docker-compose==1.29.2
dockerpty==0.4.1
docopt==0.6.2
entrypoints==0.4
fail2ban==0.10.2
feedparser==6.0.8
hachoir==3.1.3
html5lib==1.1
idna==3.3
importlib-metadata==4.11.3
importlib-resources==5.7.1
install==1.3.5
jeepney==0.8.0
jsonschema==4.4.0
keyring==23.5.0
keyrings.alt==4.1.0
lxml==4.8.0
Mako==1.2.0
Markdown==3.3.6
MarkupSafe==2.1.1
paramiko==2.10.3
prompt-toolkit==3.0.29
pyaes==1.6.1
pyasn1==0.4.8
pycairo==1.21.0
pycparser==2.21
pycrypto==2.6.1
Pygments==2.11.2
PyGObject==3.42.1
pyinotify==0.9.6
PyNaCl==1.5.0
pyrsistent==0.18.1
python-apt==1.8.4.3
python-debian==0.1.43
python-dotenv==0.20.0
pyxdg==0.27
PyYAML==6.0
requests==2.27.1
rsa==4.8
SecretStorage==3.3.2
sgmllib3k==1.0.0
six==1.16.0
soupsieve==2.3.2.post1
ssh-import-id==5.11
systemd-python==234
telegram-upload==0.5.0
Telethon==1.24.0
texttable==1.6.4
toot==0.28.0
typing_extensions==4.2.0
urllib3==1.26.9
urwid==2.1.2
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.3.2
zipp==3.8.0
```
I use a Raspbian buster.
