### ISSUE TITLE
Getting file_id of the uploaded file

### ISSUE THREAD

**Issue by cyberboysumanjay** [Nekmo/telegram-upload#15]
* telegram-upload version: 0.1.6
* Python version: 3.6
* Operating System: Pop_os

### Description
Printing the file_id of the uploaded will be handy... so that users can forward files via a bot to a specific user easily.

**Comment by Nekmo** [comment]
Added option `--print-file-id`.

**Comment by Aikanairo** [comment]
I noticed that it does not extract the file_id but file_unique_id

please how can i correct?
