### ISSUE TITLE
The --interactive option doesn't work

### ISSUE THREAD

**Issue by tissole** [Nekmo/telegram-upload#152]
* telegram-upload version: 0.5
* Python version: 3.10.3
* Operating System: Windows 10
* Dependencies list (run `pip freeze`):
cffi==1.15.0
click==8.1.2
colorama==0.4.4
cryptg==0.2.post4
hachoir==3.1.3
prompt-toolkit==3.0.29
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.21
rsa==4.8
telegram-upload==0.5.0
Telethon==1.24.0
wcwidth==0.2.5
### Description

The --interactive option doesn't show the menu for uploading or downloading files, only shows the menu for selecting chats.

### What I Did
I run telegram-upload --interactive and telegram-download --interactive
The errors
```
[Error] telegram-upload Exception:
MissingFileError: Files do not exist.
```
and
`No items were found. Exiting...`
```

**Comment by Nekmo** [comment]
Fixed. Thanks!

**Comment by 1581-netizen** [comment]
Hi Nekmo, 
I have the same problem.
Telegram-upload version: 0.5.1
OS Ubuntu 22.04

click==8.1.3
cryptg==0.3.1
DateTime==4.7
dnspython==2.2.1
hachoir==3.1.3
mongo==0.2.0
numpy==1.23.3
opencv-python==4.6.0.66
prompt-toolkit==3.0.31
pyaes==1.6.1
pyasn1==0.4.8
pymongo==4.2.0
python-magic==0.4.27
pytz==2022.2.1
rsa==4.9
telegram-upload==0.5.1
Telethon==1.25.0
wcwidth==0.2.5
zope.interface==5.4.0


```
root@vmi:/docker/pycharm# telegram-upload
[Error] telegram-upload Exception:
MissingFileError: Files do not exist.
```
