### ISSUE TITLE
The --directories recursive is not working properly

### ISSUE THREAD

**Issue by tissole** [Nekmo/telegram-upload#153]
* telegram-upload version: 0.5
* Python version: 3.10.3
* Operating System: Windows 10
* Dependencies list (run `pip freeze`):
cffi==1.15.0
click==8.1.2
colorama==0.4.4
cryptg==0.2.post4
hachoir==3.1.3
prompt-toolkit==3.0.29
pyaes==1.6.1
pyasn1==0.4.8
pycparser==2.21
rsa==4.8
telegram-upload==0.5.0
Telethon==1.24.0
wcwidth==0.2.5

### Description

The --directories recursive option is behaving strangely

### What I Did
I run `telegram-upload --to me --directories recursive "D:\Backup"`
The error

*File "D:\Backup" is empty. 
[Error] telegram-upload Exception:
MissingFileError: Files do not exist*

In is not empty, there is a folder with subfolders and files in them. I can upload only if I run the command 
`telegram-upload --to me --directories recursive "D:\Backup\Power Training Course"`

I tested with version 4.0 and is working, so the newer version introduced this behaviour.

**Comment by Nekmo** [comment]
Tried to reproduce on GNU/Linux without success:

```
telegram-load --to me --directories recursive /tmp/foobar/
Uploading "doorbell.wav"
```

Directory tree:
```
$ ls -lR
.:
total 0
drwxr-xr-x 2 nekmo users 60 may 13 00:44 sub

./sub:
total 604
-rw-r--r-- 1 nekmo users 615120 ene 24 02:09 doorbell.wav
```

**Comment by Nekmo** [comment]
@tissole more information is needed to reproduce the error. Maybe it's a bug in Windows.

**Comment by tissole** [comment]
I tried again, same error. It seems to me that the issue is related to the depth of nested folders.  My directory is like this:` D:\A\B\C\video1`. If I run `telegram-upload --to me --directories recursive D:\A`, it fails. But if I run  `telegram-upload --to me --directories recursive D:\A\B`, is working. So apparently the script doesn't go recursively more than 1 level.

**Comment by Nekmo** [comment]
Tried with two subdirectories:
```
telegram-upload --directories recursive /tmp/foobar
```

Directories:
```
$ tree
.
└── sub
    └── sub2
        └── doorbell.wav
```

-----------

Tried with three subdirectories:

```
telegram-upload --directories recursive /tmp/foobar
```

Directories:
```
$ tree
.
└── sub
    └── sub2
        └── sub3
            └── doorbell.wav
```
-----------

On GNU/Linux I can't reproduce the error @tissole . Maybe it's a Windows bug.

**Comment by tissole** [comment]
It is working in version 0.4, so 0.5 introduced some changes that caused this issue, at least on Windows.

**Comment by tissole** [comment]
I'm closing this issue because it is resolved. Funny thing is I don't know what cause it in the first place.

**Comment by tissole** [comment]
I'm sorry, I don't know what is the cause. Try to reinstall. Now is working for me.

    On Thursday, June 23, 2022 at 06:16:20 PM GMT+3, xd003 ***@***.***> wrote:  
 
 


i am facing this issue on Ubuntu sadly , unable to upload the directory
@tissole you have any idea what fixed it by any chance ?

telegram-upload --to CHATID --directories recursive --large-files split $HOME/Test gives the following error

[Error] telegram-upload Exception:
MissingFileError: Files do not exist.
