### ISSUE TITLE
Telegram premium

### ISSUE THREAD

**Issue by tapatianbeast** [Nekmo/telegram-upload#159]
What do you know about telegram premium and his 4gb file size?

**Comment by xd003** [comment]
@Nekmo can you please add 4 gb support for Premium users with all the increased limits

**Comment by xd003** [comment]
@simonlkch 
To get the premium upload working with increased limits , we just change the _MAX_FILE_SIZE_ & _CAPTION_MAX_LENGTH_ in files.py or need to do some other changes as well ?

**Comment by simonlkch** [comment]
i dont know how to debug the code.
but the concept is right. one more step for checking the user is_premium flag.

**Comment by simonlkch** [comment]
![image](https://user-images.githubusercontent.com/3492546/175571940-19e8e549-f271-4fde-a8fc-5c75119e2d11.png)

I check the source code, this project is using telethon, in telethon documention,
The User Class don't have the is_premium flag. Maybe need telethon to update their library first.

https://docs.telethon.dev/en/stable/quick-references/client-reference.html#users

**Comment by xd003** [comment]
@simonlkch thanks for info
![Picsart_22-06-24_22-12-19-890](https://user-images.githubusercontent.com/26503185/175602434-13f75751-a395-4a1f-b7ee-c0fc909156a3.jpg)

I found this on a channel , so going by this if the is_premium flag is only for indentification by bots . It shouldn't really affect us in the uploads i guess ? ( Just guessing i could be very well wrong )

**Comment by simonlkch** [comment]
just test it, telethon have set the file szie limit, so need wait telethon to upgrade

https://github.com/LonamiWebs/Telethon/blob/dd51aea4db90fd255a14e27192e221c70b45e105/telethon/_misc/utils.py#L1057

**Comment by xd003** [comment]
@simonlkch 
Can't we just easily edit that condition & then install our own version of telethon ?
pip3 install -U https://github.com/$username/telethon/archive/master.zip

**Comment by simonlkch** [comment]
> 

never say never, you can modify and try it

**Comment by xd003** [comment]
> > 
> 
> never say never, you can modify and try it

Yes indeed , thanks to all people who helped me, it should be working fine now in my fork , here it is if you need - 
```pip install https://github.com/xd003/tg/archive/master.zip```

**Comment by tapatianbeast** [comment]
This is safe? Do you fix the new format of url private channels/groups error?

**Comment by xd003** [comment]
> This is safe? Do you fix the new format of url private channels/groups error?

ID works so using that , dunno about invite url

**Comment by simonlkch** [comment]
> @simonlkch Can't we just easily fork & edit that condition & then install our own version of telethon ?
> 
> `pip3 install -U https://github.com/$username/telethon/archive/master.zip`
> 
> Also on being asked that the premium flag is missing in telethon official group , they replied this - "because premium is implemented in a layer newer than the layer the docs are written for"

Thats means install yoru version of the module?

**Comment by xd003** [comment]
> Thats means install yoru version of the module?

yes

**Comment by tapatianbeast** [comment]
> > Thats means install yoru version of the module?
> 
> 
> 
> yes

It didn't work for me, I hope Neko updates the official version

**Comment by Nideapum** [comment]
> > > 
> > 
> > 
> > never say never, you can modify and try it
> 
> Yes indeed , thanks to all people who helped me, it should be working fine now in my fork , here it is if you need - `pip install https://github.com/xd003/tg/archive/master.zip`
> 
> Just make sure to uninstall telethon before installing

Thanks, It works for me.

**Comment by santosadrian** [comment]
> 

Thank you very much, now I can upload files up to 4GB. TY sir.

**Comment by Nekmo** [comment]
Fixed in version v0.7.0.
