### ISSUE TITLE
Support Chatid Sending?

### ISSUE THREAD

**Issue by BlueSkyXN** [Nekmo/telegram-upload#160]
For example, -1001461731582 / 1461731582 (used in other tg bot/api)
When I try to use id instead of username/link, system error

ValueError: Cannot find any entity corresponding to "XXXXXXXXX"

Like this

I tried -f / --to , same problem

In addition, if the channel/group link is not public, the link format is https://t.me/+XXXXX, the same error is reported

**Comment by xd003** [comment]
> There's a pull request that adds [support ](https://github.com/Deshdeepak1/telegram-upload/blob/78066bbef1a3fae3b10a53aa19d8f5829ee67912/telegram_upload/management.py#L151) for sending files to chat ID. Only missing now is downloading from chat ID.

are you sure that it works ?
 telegram-upload --to CHAT_ID  --directories recursive --large-files split 100MB.bin gives me the following error
```TypeError: argument of type 'int' is not iterable```

**Comment by tissole** [comment]
Yes. I just run a test with "telegram-upload --to chatID "D:\Backup\New" --directories recursive --large-files split" The file is 7 GB and I see that is uploading with no errors. 


    On Thursday, June 23, 2022 at 05:23:32 PM GMT+3, xd003 ***@***.***> wrote:  
 
 



There's a pull request that adds support  for sending files to chat ID. Only missing now is downloading from chat ID.


are you sure that it works ?
telegram-upload --to CHAT_ID --directories recursive --large-files split 100MB.bin gives me the following error
TypeError: argument of type 'int' is not iterable

**Comment by Nekmo** [comment]
Duplicate of #118.
