### ISSUE TITLE
Private group/Channel Media Sending

### ISSUE THREAD

**Issue by saptarshiNandi07** [Nekmo/telegram-upload#167]
* telegram-upload version:
* Python version:
* Operating System:
* Dependencies list (run `pip freeze`):

### Description
_First things First, Top notch product!! Hats off to the Devs for creating it!_

Just want to send my media to a Private group or channel, Both does not works either thru chat ID or Invite link or anything.
Both DOES WORK if they are not kept Private (i.e. - Public Group/Channel)

However the interactive mode WORKS WELL with private groups as well. BUT looking for the same feature with normal commands...

### What I Did

Tried every possible  scenarios with Private groups and channels & Public groups and channels,
Public group/Channels always worked, Private Group/Channels never did.
Is it somehow possible? Is this a feature under DEV(looking at other issue comments) ? If Yes, when it can be released?

```
Paste the command(s) you ran and the output.
output - ValueError: Cannot find any entity corresponding to "-XXXXXXXXXXXXXX"
If there was a crash, please include the traceback here.
```

Seen a fork from
@[Deshdeepak1](https://github.com/Deshdeepak1/telegram-upload/commits?author=Deshdeepak1)
https://github.com/Deshdeepak1/telegram-upload 
However, it did not soled...

Thanks in advance!!

**Comment by dognk** [comment]
remove the (+) in your private group link and add "https://t.me/joinchat/" is working for me
