### ISSUE TITLE
.m4a is not sent as a media file

### ISSUE THREAD

**Issue by haoduck** [Nekmo/telegram-upload#169]
* telegram-upload version:0.5.1
* Python version:3.9
* Operating System:debian11
* Dependencies list (run `pip freeze`):ceph==1.0.0
cephfs==2.0.0
certifi==2020.6.20
chardet==4.0.0
click==8.1.3
crit==0.0.1
cryptg==0.3.1
dbus-python==1.2.16
distro-info==1.0
hachoir==3.1.3
httplib2==0.18.1
idna==2.10
mercurial==5.6.1
prettytable==0.7.2
prompt-toolkit==3.0.30
protobuf==3.12.4
pyaes==1.6.1
pyasn1==0.4.8
pycurl==7.43.0.6
PyGObject==3.38.0
PyJWT==1.7.1
PySimpleSOAP==1.16.2
python-apt==2.2.1
python-debian==0.1.39
python-debianbts==3.1.0
PyYAML==5.3.1
rados==2.0.0
rbd==2.0.0
reportbug==7.10.3+deb11u1
requests==2.25.1
rgw==2.0.0
rsa==4.9
six==1.16.0
telegram-upload==0.5.1
Telethon==1.24.0
unattended-upgrades==0.1
urllib3==1.26.5
wcwidth==0.2.5

### Description

.m4a is not sent as a media file, it is supported and defaulted in the official client

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Nekmo** [comment]
Hi, try the latest Telegram-upload version. In my tests the m4a files are supported:

https://docs.nekmo.org/telegram-upload/supported_file_types.html
