### ISSUE TITLE
Send video as document

### ISSUE THREAD

**Issue by KingKaitoKid** [Nekmo/telegram-upload#17]
* telegram-upload version: 0.1.6
* Python version: using Python with OS (python 2.7.10 or python3 3.6.3)
* Operating System: macOS Mojave 10.14.3 (18D42)

I'm trying to upload simple video as document but the paramet is ignored.
Just added a simple parameter when called "**send_file**" telethon's method:
`self.send_file(entity, file, caption=(name[:CAPTION_MAX_LENGTH] + '..') if len(name) > CAPTION_MAX_LENGTH else name, progress_callback=progress, force_document=True)`

video is sent as video everything I do, also tried to change the MIME but same result video is sent as video and not as document even if `force_document=True` is present.

**Comment by Nekmo** [comment]
The problem has been solved?

**Comment by KingKaitoKid** [comment]
Is not a real problem because Telegram send MP4 files as video, tried to upload MP4 video as file with macOS application (also on Android) the MP4 file was sent as video.
