### ISSUE TITLE
Experiencing slower upload speed

### ISSUE THREAD

**Issue by Nirzak** [Nekmo/telegram-upload#175]
* telegram-upload version: 0.5.1
* Python version: python 3.7
* Operating System: Ubuntu Server 22.04 LTS
* Dependencies list (run `pip freeze`):
asn1crypto==0.24.0
click==8.0.4
cryptg==0.3.1
cryptography==2.1.4
hachoir==3.1.3
idna==2.6
importlib-metadata==4.8.3
keyring==10.6.0
keyrings.alt==3.0
prompt-toolkit==3.0.30
pyaes==1.6.1
pyasn1==0.4.8
pycrypto==2.6.1
PyGObject==3.26.1
python-apt==1.6.5+ubuntu0.2
pyxdg==0.25
rsa==4.9
SecretStorage==2.3.1
six==1.11.0
telegram-upload==0.5.1
Telethon==1.24.0
typing_extensions==4.1.1
wcwidth==0.2.5
zipp==3.6.0

### Description
Experiencing very slow upload speed. I have also tested the server bandwidth speed and it's just fine. It's only telegram-upload which is comparatively slower than even telegram's own API. Please fix this. Thanks.

**Comment by Nekmo** [comment]
telegram-upload uses cryptg for encryption. Please report performance issues to the cryptg project. Thanks.

**Comment by Nekmo** [comment]
Speed improvements have been implemented in Telegram-upload v0.7.0. You can see the benchmarks with the improvement in:
https://docs.nekmo.org/telegram-upload/upload_benchmark.html
