### ISSUE TITLE
piping openssl command output

### ISSUE THREAD

**Issue by sinepgnol** [Nekmo/telegram-upload#178]
* telegram-upload version: 0.5.1
* Python version: 3.10.7
* Operating System: macOS 12.6.0 Monterey 
* Dependencies list (run `pip freeze`):

### Description

I would like to encrypt the files I upload using ideally openssl or another command and would like to pipe the output thereof to telegram-upload.
Is this somehow possible?

Thanks

**Comment by Nekmo** [comment]
Duplicated issue of #4.
