### ISSUE TITLE
error uploading video files

### ISSUE THREAD

**Issue by josha33** [Nekmo/telegram-upload#18]
* telegram-upload version: recent stable 0.1.6
* Python version: 3.6 using scl repo
* Operating System: linux Centos 6

### Description

I get this error when trying to upload video files (i can upload other file types ):
http://prnt.sc/mv498h

I installed the ffmpeg 4.1.1 .

**Comment by Nekmo** [comment]
The error should already be fixed, update to the latest version. If you follow the error paste information about the video.

```shell
$ pip install -U telegram-upload
```

**Comment by josha33** [comment]
This is what i get when i try to update :   http://prnt.sc/mwkbte
I have the requirements installed.

**Comment by Nekmo** [comment]
Thanks for your reply, this is an error introduced in the latest version. I'm going to fix it today. Thanks.

**Comment by Nekmo** [comment]
Fixed! Thanks!

**Comment by josha33** [comment]
Thank you! everything's working fine now.

**Comment by Nekmo** [comment]
You are welcome :)
