### ISSUE TITLE
Choosing folder to download

### ISSUE THREAD

**Issue by Wajalot** [Nekmo/telegram-upload#183]
* telegram-upload version:  latest
* Python version: latest
* Operating System: Debian 11
* Dependencies list (run `pip freeze`):

### Description

Is there any way to choose the folder to download using telegram-download? It is home by default, but would be better to choose the folder.

Thanks

**Comment by Nekmo** [comment]
Change current directory to download directory. For example:

```
cd /path/to/download/dir
telegram-download ...
```
