### ISSUE TITLE
Use with django?  Cannot import any methods 

### ISSUE THREAD

**Issue by Nitesh-mint** [Nekmo/telegram-upload#186]
* telegram-upload version: 0.5.1
* Python version: 3.10.6
* Operating System: Ubuntu 

### Description
I want to use it with my django app but i am not able to call any methods.Can you please help me with the methods that i can use it with my django app.

###Log
```
from telegram_upload import upload_file
ImportError: cannot import name 'upload_file' from 'telegram_upload'
```

**Comment by Nekmo** [comment]
Hi, you have to look at how telegram-upload works in the `management.py` file. There you will see how a `Client` instance is created.

https://github.com/Nekmo/telegram-upload/blob/master/telegram_upload/management.py

In this file you will find examples of the executed methods.

Regards.

**Comment by Nekmo** [comment]
Closed due to inactivity.
