### ISSUE TITLE
uploading video files with delay

### ISSUE THREAD

**Issue by josha33** [Nekmo/telegram-upload#19]
* telegram-upload version:latest 0.1.9
* Python version:3.6
* Operating System:linux centos 6

### Description
First of all thanks for the great tool! 
You already fixed uploading video files in the previous issue thank you again for that!
What I encountered is that when I try to upload a video file it starts with delay! and the bigger the video file the bigger the delay becomes! for example, if I wanna upload a 600MB video file there's like 10 minutes delay before uploading that video file! like its uploading twice or something like that! there's no error or something just the delay before uploading video files.
Uploading other file types like archives don't have this issue.

**Comment by Nekmo** [comment]
The delay is due to the time to get the thumbnail of the video. I have to improve it... I hope to have it fixed soon.

**Comment by anzilr** [comment]
Is it possible to upload video as document file? Now it's uploading video as video and no thumbnail 😐. Anyway, thanks for this great tool bro😉

**Comment by Nekmo** [comment]
Fixed!

**Comment by josha33** [comment]
Thank you very much. Working great!
