### ISSUE TITLE
Support multi part streamable mp4 while using "--large-files split"

### ISSUE THREAD

**Issue by arkaroy14** [Nekmo/telegram-upload#192]
### Description

I am trying to upload any mp4 whose size > 2gb so here i am using "--large-files split". But using this command mp4 uploading in various parts files but they are not streamable. 

### What I Did

```
telegram-upload --to me 'input.mp4' --large-files split
```
Ex: here i am trying to upload 2.5gb mp4 to telegram using this command it splitting into 2 files 2gb and 500 mb but both showing as files not able to stream.

**Comment by arkaroy14** [comment]
To solve this issue i had used **mp4box** module along with **telegram-upload** .
First i checked,
if **file size greater than 2 gb** then check **if filename is mp4** use **mp4box split** and upload those split using telegram-upload.
else other format video, **convert into mp4 using ffmpeg** then used mp4box split and telegram-upload to again upload all split files. 
It will be good if this feature can be merged to telegram-upload to easy upload large video files as streamable.

**Comment by lapidu** [comment]
Hello @arkaroy14,
I have the same problem. Could you provide me with your code? 

Thank You

**Comment by SoravKu** [comment]
@arkaroy14 You can try this: https://GitHub.com/TheCaduceus/tg-upload

**Comment by arkaroy14** [comment]
@lapidu i have used very basic commands here and used pyrogram as it's giving very good speed. Telethon speed much lower. I have added thumbnail, also after upload duration now showing in telegram those wasn't working for me if i used TheCaduceus tg-upload. 
Check my code below
https://github.com/arkaroy14/tg-pyrogram-upload

**Comment by SoravKu** [comment]
> @lapidu i have used very basic commands here and used pyrogram as it's giving very good speed. Telethon speed much lower. I have added thumbnail, also after upload duration now showing in telegram those wasn't working for me if i used TheCaduceus tg-upload. Check my code below https://github.com/arkaroy14/tg-pyrogram-upload

Check v1.0.9 release of tg-upload:
https://github.com/TheCaduceus/tg-upload/releases

**Comment by arkaroy14** [comment]
@SoravKu nice copy paste of my code. Nice clang keep going copying others work
