### ISSUE TITLE
Change to pyrogram

### ISSUE THREAD

**Issue by poliandro** [Nekmo/telegram-upload#195]
Telethon is slow when uploading files because it does so by uploading the file chunks sequentially, rather than in parallel, how the pyrogram does. The telethon developer has no interest in changing this. Uploading with pyrogram is 5–10 times faster than using telethon.

Also, the pyrogram code is much simpler and easier to work with. Rather than using hacks like fastTelethon, this solution is an alternative to #140 and resolves the low speed by default.

**Comment by SoravKu** [comment]
@poliandro There is a [repo](https://github.com/TheCaduceus/tg-upload) similar to telegram-upload that uses program.

**Comment by poliandro** [comment]
@SoravKu Thank you for the suggestion. @Nekmo I'm glad you work again on this project. I will wait for next version, with faster speed.

**Comment by Nekmo** [comment]
Speed improvements have been implemented in Telegram-upload v0.7.0. You can see the benchmarks with the improvement in:
https://docs.nekmo.org/telegram-upload/upload_benchmark.html
