### ISSUE TITLE
Upload directories

### ISSUE THREAD

**Issue by Nekmo** [Nekmo/telegram-upload#2]

**Comment by maximvid** [comment]
This would be super helpful, I have a 1.5tb torrent that needs uploading to a channel but it's split into 1344 different folders

**Comment by erotavlas85** [comment]
Hi,
do you have any ETA for releasing this feature?
Thank you

**Comment by Nekmo** [comment]
> Hi,
> do you have any ETA for releasing this feature?
> Thank you

Right now I'm going through a lot of work, but I want to release a new version soon.

**Comment by Telematica** [comment]
Are files uploaded to "Saved Message" by default?

**Comment by Telematica** [comment]
> Are files uploaded to "Saved Message" by default?

Never mind, just figured it out.

**Comment by Nekmo** [comment]
Solved in master. Pending upload to Pypi

**Comment by alfredonodo** [comment]
Thank for it. Does it work recursively?
`telegram-upload --to me --directories recursive rootFolder`
It just uploads the files on the rootFolder.

**Comment by Nekmo** [comment]
Opened new issue #37

**Comment by Nekmo** [comment]
Fixed in development branch! @alfredonodo

**Comment by cristian64** [comment]
Hey Nekmo,

I was giving the `--directories recursive` option a go. It seems to work well.

However, I noticed that it does not sort files alphabetically. For science, I applied the following patch to my local checkout:

```diff
--- telegram_upload/files.py
+++ telegram_upload/files.py
@@ -74,8 +74,10 @@
     def get_iterator(self):
         for file in self.files:
             if os.path.isdir(file):
-                yield from map(lambda file: file.path,
-                               filter(lambda x: not x.is_dir(), scantree(file, True)))
+                for dirpath, dirnames, filenames in os.walk(file, followlinks=True):
+                    dirnames.sort()
+                    for filename in sorted(filenames):
+                        yield os.path.join(dirpath, filename)
             else:
                 yield file
 ```

By using `os.walk()`, the directory names can be sorted in-place to drive the order in which the directories will be traversed (see https://docs.python.org/3/library/os.html#os.walk). Also the file names are sorted.

With this, one could use the `--directories recursive` option even with a flat directory, and it'd make uploading directories in alphabetical order in Windows a bit easier.

This would make `scantree()` and `scandir()` redundant. Typically I would have created a PR, but I'm not sure if there were arguments for implementing it that way.

**Comment by prisonerr627** [comment]
> Hey Nekmo,
> 
> I was giving the `--directories recursive` option a go. It seems to work well.
> 
> However, I noticed that it does not sort files alphabetically. For science, I applied the following patch to my local checkout:
> 
> --- telegram_upload/files.py
> +++ telegram_upload/files.py
> @@ -74,8 +74,10 @@
>      def get_iterator(self):
>          for file in self.files:
>              if os.path.isdir(file):
> -                yield from map(lambda file: file.path,
> -                               filter(lambda x: not x.is_dir(), scantree(file, True)))
> +                for dirpath, dirnames, filenames in os.walk(file, followlinks=True):
> +                    dirnames.sort()
> +                    for filename in sorted(filenames):
> +                        yield os.path.join(dirpath, filename)
>              else:
>                  yield file
> By using `os.walk()`, the directory names can be sorted in-place to drive the order in which the directories will be traversed (see https://docs.python.org/3/library/os.html#os.walk). Also the file names are sorted.
> 
> With this, one could use the `--directories recursive` option even with a flat directory, and it'd make uploading directories in alphabetical order in Windows a bit easier.
> 
> This would make `scantree()` and `scandir()` redundant. Typically I would have created a PR, but I'm not sure if there were arguments for implementing it that way.

Hello are you still maintaining it? and have you created the directory upload? in your repo i says 1.5GB can be uploaded instead of 2GB?
