### ISSUE TITLE
Can't upload video as Document.

### ISSUE THREAD

**Issue by anzilr** [Nekmo/telegram-upload#20]
* telegram-upload version:0.1.9
* Python version:3.6
* Operating System:ubuntu 16.4 Server LTS

### Description

How can I upload video files as document file. Now it's in video format.

**Comment by Nekmo** [comment]
Why is this necessary?

**Comment by MRACHINI** [comment]
i don't think sending video preserves file name, sending as document does.

**Comment by Nekmo** [comment]
Available in the development branch. A new parameter `--force-file` has been added.
