### ISSUE TITLE
Encountered a strange problem

### ISSUE THREAD

**Issue by nitezs** [Nekmo/telegram-upload#210]
Python Version: 3.10.9
Telegram-upload Version: 0.7.0
Operating System: Windows 10
Dependencies list:
```
click==8.1.3
colorama==0.4.6
cryptg==0.4.0
hachoir==3.2.0
more-itertools==9.1.0
prompt-toolkit==3.0.38
pyaes==1.6.1
pyasn1==0.5.0
PySocks==1.7.1
rsa==4.9
telegram-upload==0.7.0
Telethon==1.28.5
wcwidth==0.2.6
```
---
I used to be able to use it normally, but I have had problems in the past few days.
When I used `telegram-upload` to upload some files, I got some errors message.
```
Server sent a very new message with ID 7253350956018624521, ignoring (see FAQ for details)
Server sent a very new message with ID 7253350956046503937, ignoring (see FAQ for details)
```
And I Stop it with Ctrl+C
```
Aborted!
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\connection\connection.py:313> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\connection\connection.py:332> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\mtprotosender.py:462> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\telethon\network\mtprotosender.py:505> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Exception ignored in: <coroutine object Connection._recv_loop at 0x0000018986F913F0>
RuntimeError: coroutine ignored GeneratorExit
```

**Comment by Nekmo** [comment]
Maybe this is not an error. Have you tried ignoring the message?

**Comment by nitezs** [comment]
> 

I tried to wait, but nothing was output. The file was not uploaded successfully.

**Comment by Nekmo** [comment]
Has the problem happened again?

**Comment by Nekmo** [comment]
I found this link about this: https://stackoverflow.com/questions/75332067/error-messages-clogging-telethon-resulting-server-sent-a-very-new-message-xxxx

Is your system datetime correct?

**Comment by nitezs** [comment]
> I found this link about this: https://stackoverflow.com/questions/75332067/error-messages-clogging-telethon-resulting-server-sent-a-very-new-message-xxxx
> 
> Is your system datetime correct?

I use the UTC time zone and there is no problem with the time.

**Comment by Nekmo** [comment]
Does the problem occur all the time or has it only happened once?

**Comment by nitezs** [comment]
> Does the problem occur all the time or has it only happened once?

This issue has been occurring since July 6th, and once uploaded, this error prompt will appear. Previously, it could be used normally.

**Comment by Nekmo** [comment]
Can you try with an old telegram-upload version? For example:

```bash
$ pip install telegram-upload==0.6.1
```

**Comment by nitezs** [comment]
> Can you try with an old telegram-upload version? For example:
> 
> ```shell
> $ pip install telegram-upload==0.6.1
> ```

I also encountered the same problem using the old version.

**Comment by Nekmo** [comment]
Check that they are not one of these other reasons:
https://stackoverflow.com/a/75948500

**Comment by nitezs** [comment]
> Check that they are not one of these other reasons: https://stackoverflow.com/a/75948500

I did not use a system proxy. 
I logged out all device accounts and deleted the configuration files. Then I logged back into Telegram-upload. 
I tried to change the time zone of my computer （with automatic time setting）
Still encountering the same problem。

**Comment by nitezs** [comment]
I am trying to use Telegram-upload on another device and everything is working properly. It's strange.

**Comment by nitezs** [comment]
I have changed my account and it is running normally.
But I still don't know why my previous account cannot be used normally on this computer (it can be used normally on other computers)
Thank you for your help.

**Comment by Nekmo** [comment]
You are welcome :) I'm glad the problem has been resolved.
