### ISSUE TITLE
Feature request - Continously monitor chat and download it to local

### ISSUE THREAD

**Issue by fatmeat** [Nekmo/telegram-upload#211]
Hello Nekmo, thank you for this amazing project, I have some idea base on my personal usage in below

### Description

I was wondering if it's worth to develop continous monitor chat feature that able to monitor specific chat/channel for newly upload files and download it to local, I am asking for this because I wrote a python to do this work with TG Bot, but at the end of the day I found Bot API limiting file size to 20MB, as I searching for alternative in internet, I then landed to your amazing project.

I know I can do a schedule job to run "telegram-download --delete-on-success" to archive similar goal but I think it would be better to use the native parameter to do this? Let me know your thought, thanks!!

**Comment by fatmeat** [comment]
Thank you for reply, looking forward for it goes to public.

I will make it my own way at this moment.

**Comment by Nekmo** [comment]
You are welcome :)
