### ISSUE TITLE
Getting Sent a new message error while uploading a file

### ISSUE THREAD

**Issue by forswearadidas** [Nekmo/telegram-upload#220]
* telegram-upload version:  0.7.1
* Python version: 3.9
* Operating System: Win 10
* Dependencies list (run `pip freeze`):

### Description
Earlier it used to work but now i am receiving this message when ever i try to upload and uploading stuck with this message
**Server sent a very new message with ID 7274298913954252805, ignoring**
**Server sent a very new message with ID 7274298913977566209, ignoring**
**Server sent a very new message with ID 7274304139673625601, ignoring
Security error while unpacking a received message: Too many messages had to be ignored consecutively**

First i got this message in old version so i updated the telegram-upload but still showing error in new version and tried changing to different account still got the same error while uploading

### What I Did

telegram-upload filename 

Got this message and stuck for it long
**Server sent a very new message with ID 7274298913954252805, ignoring**
**Server sent a very new message with ID 7274298913977566209, ignoring**
**Server sent a very new message with ID 7274304139673625601, ignoring
Security error while unpacking a received message: Too many messages had to be ignored consecutively**

i tried to upload a file to test if working or not

**Comment by Nekmo** [comment]
Hi,

This error is normally because you have the hour of your computer behind or
ahead.

https://github.com/Nekmo/telegram-upload/issues/210

Regards,

**Comment by forswearadidas** [comment]
Thanks @Nekmo for the solution. 
I got to know my system time was few minutes behind from current time. 
Fixed it and the uploading was happening..

Thanks for the help and great tool.
