### ISSUE TITLE
How to install and use in windows?

### ISSUE THREAD

**Issue by shadow443** [Nekmo/telegram-upload#24]
* telegram-upload version: 0.1.10
* Python version: 3.7.2
* Operating System: Windows 10 64bit

### Description
Hello, i try to install via "pip install telegram-upload". If I run python telegram-upload it says "python: can't open file 'telegram-upload': [Errno 2] No such file or directory". And if I only run telegram-upload cmd doesn't recognize it (it's because it's not in the environment variables I don't know where the installation was done.)

### My Question
Does telegram-upload only work on linux?  Is there any way to install it and use it in windows?

Thanks for the help.

**Comment by Nekmo** [comment]
There are other users who have used telegram-upload in Windows. I have not tried Windows support because it is a system that can not be tested using CI.

I know it works in Windows, but I do not know how it works in Windows. Sorry.

**Comment by juanspeed** [comment]
@Nekmo I just fixed it. The script is in this directory:
"C:Users\username\AppData\Local\Programs\Python\Python37-32\Scripts"
 
I used python telegram-upload and was able to configure api and hash.

I did some audio and video test uploads and they were successfully uploaded. Thank you.

**Comment by nikotz** [comment]
how fix the installation? i have the same issue

**Comment by Nekmo** [comment]
Windows does not support scripts without an extension. This is a known issue in this OS. In a future version I will try to support it.

**Comment by nikotz** [comment]
Already fixed, the problem is pip something about add "" in this line #!"c:\users\nikotz\appdata\local\programs\python\python36\python.exe" " when you add it change extension to py and call it in the cmd telegram-upload.py  and works perrrrfect

**Comment by Nekmo** [comment]
Added entry_point console_script. It should now work fine on Windows. Will be available in the next release.

**Comment by gmy77** [comment]
Why Telegram (base) work native on Windows and Telegram-X not? Is so difficult to build this? And sorry if this for certain guys try to think "noob question..." but as me, considering the base version and the x version... the difference on the base code is tiny... for x the real differences are on all things the base don't have... for this i ask...
