### ISSUE TITLE
Need Heroku support 

### ISSUE THREAD

**Issue by telegrambotdev** [Nekmo/telegram-upload#25]
need support for heroku.is anyway to deploy this code on heroku ?

**Comment by Nekmo** [comment]
I have never used Heroku, but I will look at how to do it :+1:

**Comment by ssoorajr** [comment]
Thank you nekmo.Because heroku is very user friendly to beginners ,so i can also use your code.

you can take a look at sample heroku [project here](https://github.com/SpEcHiDe/AnyDLBot)

**Comment by rsoorajs** [comment]
Thank you nekmo.Because heroku is very user friendly to beginners ,so i can also use your code.

you can take a look at sample heroku [project here](https://github.com/SpEcHiDe/AnyDLBot) & [this](https://github.com/Quiec/fileassistantbot)

**Comment by rsoorajs** [comment]
still no updates ?

**Comment by Nekmo** [comment]
I do not understand why Heroku can be useful for this project. The maximum size on Heroku is 300MiB-500MiB. This project is for working with large files. Why download the files inside Heroku? Can the files then be downloaded from Heroku?

**Comment by rsoorajs** [comment]
because heroku is a top rated app deploying platform.also herokku support big files ..not just(300mb)..
yeah we can download our files from heroku

**Comment by Nekmo** [comment]
@telegrambotdev telegram-upload is a cli application and Heroku is for serve web apps. I have been looking for documentation to create command line applications on Heroku with no success.
