### ISSUE TITLE
Installation Error - hachoir3

### ISSUE THREAD

**Issue by prdpjngd** [Nekmo/telegram-upload#26]
* telegram-upload version:
* Python version:
* Operating System:

### error showing 

  ERROR: Could not find a version that satisfies the requirement hachoir3 (from telegram-upload) (from versions: none)
ERROR: No matching distribution found for hachoir3 (from telegram-upload)

**Comment by Nekmo** [comment]
It seems that hachoir3 has been deleted from Pypi. But hachoir may be an alternative.

https://pypi.org/project/hachoir/

I will check it, thanks!

**Comment by Nekmo** [comment]
Ok, `hachoir` works. Soon a new version will come out changing the requirement.

**Comment by Nekmo** [comment]
Fixed.
