### ISSUE TITLE
caption can with hyperlink？

### ISSUE THREAD

**Issue by itgoyo** [Nekmo/telegram-upload#263]
* telegram-upload version:
* Python version:
* Operating System:
* Dependencies list (run `pip freeze`):

### What I Did

```
telegram-upload -p http://127.0.0.1:7890 --to @aaaaaa --print-file-id demo.mp4 --caption "#tag2 #tag2 clicktojump<a href="https://www.runoob.com/">runoob</a>"
```
<img width="461" alt="image" src="https://github.com/Nekmo/telegram-upload/assets/23348551/06b11ee6-8bc9-4b50-a0c4-eefab7a2e675">

**Comment by Nideapum** [comment]
You can use Markdown format
`[text](url)`
