### ISSUE TITLE
Problem with sending file using $ characters in filename 

### ISSUE THREAD

**Issue by hamedhjz** [Nekmo/telegram-upload#27]
* telegram-upload version: 0.2.0
* Python version: 3.7.3
* Operating System: debian 10
* all of other python libs are uptodate
### Description

when i download the video from youtube using by youtube-dl and sending it to telegram:
if the name was like "video name $9 test.mp4" there was a error like file not found and file name became like this in the python "video name 9 test.mp4"

### What I Did
i think there is a problem with click that remove the $ character

**Comment by Nekmo** [comment]
Are you escaping `$` symbol? For example:

```
(telegram-upload) [nekmo@homura ~/Workspace/telegram-upload] (master)$ ./scripts/telegram-upload 'cFw$gRXlxNTozt4kuQm9@@hd.mp4' 
Uploading cFw$gRXlxNTozt4kuQm9@@hd.mp4  [####################################]  100%             
```

And:
```
(telegram-upload) [nekmo@homura ~/Workspace/telegram-upload] (master)$ ./scripts/telegram-upload cFw\$gRXlxNTozt4kuQm9@@hd.mp4 
Uploading cFw$gRXlxNTozt4kuQm9@@hd.mp4  [####################################]  100%             
```

**Comment by hamedhjz** [comment]
oh thanks i have used " instead of ' and now work perfectly

**Comment by Nekmo** [comment]
You are welcome :+1:
