### ISSUE TITLE
Option to forward uploaded file

### ISSUE THREAD

**Issue by ptts** [Nekmo/telegram-upload#29]
### Description

It would be great to have the option to automatically forward the file to other chat_ids after the upload is complete.

Telethon directly supports forwarding messages:
```
client.forward_messages(
    entity,  # to which entity you are forwarding the messages
    message_ids,  # the IDs of the messages (or message) to forward
    from_entity  # who sent the messages?
)
```
(Source: [https://telethonn.readthedocs.io/en/latest/extra/examples/working-with-messages.html](https://telethonn.readthedocs.io/en/latest/extra/examples/working-with-messages.html))

The function could be implemented with another "-F " / "--forward" flag that takes a list of comma separated chat_ids to which the uploaded file/message should be forwarded.

`telegram-upload /path/to/file.txt --print-file-id --forward 123456,-987654`

**Comment by Nekmo** [comment]
It will be included in the next release. :)

**Comment by Nekmo** [comment]
Added to the new release! It can be tested in the development branch.

Thanks!
