### ISSUE TITLE
No preview video.

### ISSUE THREAD

**Issue by vladios13** [Nekmo/telegram-upload#31]
* telegram-upload version: 0.2.1
* Python version: Python 3.5.3
* Operating System: Debian 9

### Description
When I download a .mp4 video, I don't get a preview of it. 
I just see the background of this video being washed up. It's like the screenshot below. 
![IMG_20200210_205740](https://user-images.githubusercontent.com/10531221/74176399-a5214a00-4c48-11ea-89af-a3f267c7acd8.jpg)

I wish the video had some kind of preview.

**Comment by Nekmo** [comment]
Do you have ffmpeg installed on your computer?

**Comment by vladios13** [comment]
> Do you have ffmpeg installed on your computer?

Yes, of course it's installed in the system. The latest version is being used: `ffmpeg is already the newest version (7:3.2.14-1~deb9u1).`

I upload the .mp4 video from YouTube via youtube-dl, and then upload it to Telegram. But I can't see the preview.

**Comment by vladios13** [comment]
Is there a solution to this problem?

**Comment by Nekmo** [comment]
I was able to reproduce the error.

![6a2346f2-b2ac-4807-831d-cabf6b0cfd5b](https://user-images.githubusercontent.com/740106/78730995-b0d67780-793e-11ea-8a44-a8f3b666121d.jpeg)

I'm investigating it, thanks!

**Comment by Nekmo** [comment]
For some reason now Telegram doesn't show small thumbnails. I have made some changes and now I think it should work.

**Comment by Nekmo** [comment]
Closed due to inactivity.
