### ISSUE TITLE
'The sqlite3 module is not available under this'

### ISSUE THREAD

**Issue by bpo5r5** [Nekmo/telegram-upload#32]
* telegram-upload version: 0.2.1
* Python version: 3.6.6
* Operating System: Ubuntu 16.04

### Description

When invoking the telegram-upload command, I get this following error:

```
/home/bpo5r5/.pyenv/versions/3.6.6/lib/python3.6/site-packages/telethon/client/telegrambaseclient.py:219: UserWarning: The sqlite3 module is not available under this Python installation and no custom session instance was given; using MemorySession.
You will need to re-login every time unless you use another session storage
  'The sqlite3 module is not available under this '
Please enter your phone:
```

### What I Did

```
telegram-upload
```

I'd like to save my log-in instance so I do not have to every time I upload a file.

**Comment by Nekmo** [comment]
Install the sqlite3 dependencies.

```
sudo apt-get install libsqlite3-dev
```

https://stackoverflow.com/questions/8628774/python-3-2-cant-import-sqlite3-module

**Comment by bpo5r5** [comment]
@Nekmo thank you
