### ISSUE TITLE
edit file name

### ISSUE THREAD

**Issue by nikotz** [Nekmo/telegram-upload#33]
* telegram-upload version:1.2.1
* Python version:3.7
* Operating System:win/mac

### Description
how a i can change or add more text to label, like add url or bold font
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Nekmo** [comment]
It is not possible yet. It is an interesting feature.

**Comment by Nekmo** [comment]
Added to the development version. Will be available in the next release!

**Comment by nikotz** [comment]
tnks!!!
