### ISSUE TITLE
Selective downloading option

### ISSUE THREAD

**Issue by vaibhavreddys** [Nekmo/telegram-upload#34]
The option of allowing the user to select the choice of files to download would be better.
Suppose, consider if a user has many files uploaded and doesn't want to download all of them immediately, and instead wants only one/few specific files to be downloaded.

Providing a selective file download option would solve this requirement.

**Comment by Nekmo** [comment]
It is a good idea, and it is planned, although it is difficult to implement.

The recommendation right now is to use the chat "saved messages". Forward the files to download. Telegram-download will download the latest files until it finds a message without a file.
