### ISSUE TITLE
caption style syntax

### ISSUE THREAD

**Issue by nikotz** [Nekmo/telegram-upload#39]
* telegram-upload version:0.3
* Python version:3.7
* Operating System:macos/win

### Description

The caption have styles? or documentation about it?

**Comment by Nekmo** [comment]
Hi, you can use the markdown syntax, just like on your mobile. For example `**bold**`

**Comment by gokaybiz** [comment]
How can i make new lines?

**Comment by Nekmo** [comment]
@gokaybiz you can use line break on your console. Just don't close the quotes. For example:

```
$ telegram-upload --caption "Foo <press enter>
Bar"<press enter again>
```

Or in a single line:

```
$ telegram-upload --caption "Foo"$'\n'"Bar"
```

**Comment by Nekmo** [comment]
Ask to reopen the issue if you need to.
