### ISSUE TITLE
not using system HTTP Proxy

### ISSUE THREAD

**Issue by mozaffari** [Nekmo/telegram-upload#40]
* telegram-upload version: 0.3.1
* Python version:3
* Operating System: Ubuntu 18.04

### Description

I can not find any way on how to set up an HTTP proxy for telegram-upload.
Also it is not following the system HTTP proxy.

**Comment by Nekmo** [comment]
Added to v0.4.0 milestone!

**Comment by Nekmo** [comment]
Resolved in `master` branch :)

To install it use:

```
pip install https://github.com/Nekmo/telegram-upload/archive/master.zip
```

Thanks!
