### ISSUE TITLE
Although I have faster bandwidth upload is too slow!!

### ISSUE THREAD

**Issue by ashish453** [Nekmo/telegram-upload#42]

**Comment by temporhodes** [comment]
same for me.
one same server i have installed userbots ( uniborg-userge-...) and telegram-upload.
i uploaded a 500 MB file.they uploaded it in about 40 seconds but telegram-upload took about 4 minutes.
may you pls make it faster if it is possible ? tnx.

**Comment by Nekmo** [comment]
Telegram-upload uses Telethon and cryptg to upload files. You can open an incident in their repositories to request more help, sorry.

If you think it is a Telegram-upload error, I need more information. I will reopen the assignment when there are more details, thanks.

**Comment by Nekmo** [comment]
Speed improvements have been implemented in Telegram-upload v0.7.0. You can see the benchmarks with the improvement in:
https://docs.nekmo.org/telegram-upload/upload_benchmark.html
