### ISSUE TITLE
Caption problem

### ISSUE THREAD

**Issue by temporhodes** [Nekmo/telegram-upload#44]
in latest version the caption has problem.
i have 10 videos in a folder all mp4.i run this command:
telegram-upload *.mp4
the captions should be the file name, but all of them are the name of the first file.

thanks.

**Comment by Nekmo** [comment]
This bug will be fixed in the next release. Thanks for your report!

**Comment by Nekmo** [comment]
Fixed! It will be included in the next release. To upgrade to the patched version:

```
pip install https://github.com/Nekmo/telegram-upload/archive/master.zip 
```

**Comment by Nekmo** [comment]
Released!
