### ISSUE TITLE
[FEATURE] Support 2GB uploads. 

### ISSUE THREAD

**Issue by xscd** [Nekmo/telegram-upload#46]
* telegram-upload version: v0.3.1
* Python version: Python 3.6.9
* Operating System: Ubuntu 18.04.4 LTS

### Description
I tried to upload a file between 1.5GB - 2GB but failed. Telegram will start to support uploading up to 2 GB files. I would like this to be implemented in telegram-upload.

Source and Proof: https://t.me/tginfoen/884

**Comment by phanirithvij** [comment]
I think there's no need to change any code here. The telethon lib has got it https://github.com/LonamiWebs/Telethon/commit/bfb8de2736959f586cb9f527faf1fd6eca08f742

**Comment by Nekmo** [comment]
Thanks @phanirithvij !
