### ISSUE TITLE
Issue when uploading file (photo)

### ISSUE THREAD

**Issue by bryanseah234** [Nekmo/telegram-upload#48]
* telegram-upload version: 0.32
* Python version: 3.8
* Operating System: win10

### Description

i tried to upload an image from my computer to a telegram grp chat

### What I Did

```

code input:
telegram-upload --to t.me/nric2003 C:\Users\*\Desktop\*\*\*\T0362678J.png
code output:
https://user-images.githubusercontent.com/66017805/87990821-59d46700-cb17-11ea-99d5-4d5f40396d8f.png

```

**Comment by Nekmo** [comment]
Try deleting the `telegram-upload.session` file. Telegram-upload is not tested on Windows, sorry.

**Comment by bryanseah234** [comment]
Hahaha okay! I will try again. Thankyou

**Comment by Nekmo** [comment]
Did you get it to work?

**Comment by Nekmo** [comment]
Closed due to inactivity.
