### ISSUE TITLE
verification code

### ISSUE THREAD

**Issue by danielalejandroamaro** [Nekmo/telegram-upload#51]
* telegram-upload version: 0.3.2
* Python version: 3
* Operating System: linux

### Description
![Annotation 2020-08-14 135011](https://user-images.githubusercontent.com/26387903/90278317-44600d80-de35-11ea-821a-517d00333eb6.png)

i never receive the verification code 🤷‍♂️🤷‍♂️
```

**Comment by naninaveen** [comment]
Have you tried entering your mobile number in the international format? (e.g. +91xyzxyzxyzx)

**Comment by zakaryan2004** [comment]
Can confirm; tested with 2 phone numbers, both phone numbers written on International Format with Country Code in the beginning. This doesn't happen in other scripts and projects using Telethon. The custom Client may be to blame.

**Comment by Nekmo** [comment]
```
(telegram-upload) [nekmo@homura ~/Workspace/telegram-upload] (master)$ telegram-upload /home/nekmo/amazon-dash.png
Go to https://my.telegram.org and create a App in API development tools
Please Enter api_id: ******
Now enter api_hash: ********************************
Please enter your phone: +346********
Please enter the code you received: 81793
Please enter your password: 
Signed in successfully as Nekmo
```

I have not been able to reproduce it. Telethon version: `Telethon==1.17.5`. Telegram-upload version: `master branch`.

**Comment by jyeros** [comment]
I had the same issue with version 0.4.0, code never sent, I installed directly from the master branch and it works as expected.

**Comment by Nekmo** [comment]
Closed due to inactivity.
