### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by Sanfe** [Nekmo/telegram-upload#60]
* telegram-upload version:0.3.3
* Python version:3.85
* Operating System:Arch linux Arm64

### Description

the install script fail to install

![IMG_20200926_194222_759](https://user-images.githubusercontent.com/1896094/94346977-ae70f280-0030-11eb-8df0-bd60b2a10dbc.jpg)

###  What i Did
 sudo pip3 install -U telegram upload

**Comment by Nekmo** [comment]
Hi, you are missing packages to compile on your distro. In the error message you can read that the gcc package is missing.

**Comment by Nekmo** [comment]
Closed due to inactivity.
