### ISSUE TITLE
Custom Thumbnail For the Files getting Uploaded

### ISSUE THREAD

**Issue by Rockybhaayi** [Nekmo/telegram-upload#65]
* telegram-upload version: 0.3.3
* Python version: Python 3.7.7
* Operating System: Ubuntu 18.04.4 LTS

### Description

Hi
I have Multiple files inside a common Folder (1000)
I am tying to Upload all of them with a common custom Thumbnail
Is it possible to do that?
Thank you

**Comment by Nekmo** [comment]
Currently not possible, but it is an interesting feature. It will be available in a future release.

**Comment by roshanconnor123** [comment]
Thank you for that
Will eagerly wait for that
Stay safe
