### ISSUE TITLE
how to re-verify when i type in wrong app-id

### ISSUE THREAD

**Issue by boluohong** [Nekmo/telegram-upload#66]
* telegram-upload version:latest
* Python version:20.2.4
* Operating System:debian 9

### Description
hello
i install this program successfully
but when i type in the App api_id/api_hash , i do it wrong.
i want to re-verify, but it cant. 
and i dont know how to do it

i dont konw how to uninstall it and then re-install it
please help me if someone know it

thank for your time

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by boluohong** [comment]
it keep me to type the phone number and then tell me the app-id is wrong 
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)

i know that 
i want to censor the App api_id/api_hash
but i dont know how to do

**Comment by Nekmo** [comment]
Delete `~/.config/telegram-upload.json` file in your computer.

**Comment by Nekmo** [comment]
Now both codes are validated.
