### ISSUE TITLE
Unable to convert string to Unicode: 'ascii' codec can't decode byte 0xab in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by ShubhamKarala** [Nekmo/telegram-upload#68]
* telegram-upload version: 0.3.4
* Python version: 3.8.5
* Operating System: Linux Mint

### Description

while using --print-file-id option, the script sometimes doesn't output file_id and outputs this strange error.
```
[warn] [/file[0]/uid] Unable to convert string to Unicode: 'ascii' codec can't decode byte 0xab in position 0: ordinal not in range(128)
```

**Comment by Nekmo** [comment]
@ShubhamKarala the message is a warning but I don't know which library causes it. It is not related to the use of `--print-file-id` argument.

**Comment by Nekmo** [comment]
Ok, these warns are triggered by hachoir:

https://stackoverflow.com/questions/38832691/suppress-warnings-in-hachoir

**Comment by Nekmo** [comment]
Fixed in `master` branch, thanks!

This change will be available very soon in Pypi. Meanwhile you can install it using:

```
$ pip install https://github.com/Nekmo/telegram-upload/archive/<branch>.zip
```
