### ISSUE TITLE
Move my login information

### ISSUE THREAD

**Issue by temporhodes** [Nekmo/telegram-upload#71]
Hello.

Can i move my login information from one device to another for preventing new login ?

I have logged in one session in Termux app on my phone, now i want to use this session on my linux server too without logging in again.

Is there any way ?

Thanks.

**Comment by Nekmo** [comment]
Hi @terminate9298 ,you have the answer in the README:

```
Credentials are saved in ~/.config/telegram-upload.json and ~/.config/telegram-upload.session. You must make sure that these files are secured. You can copy these files to authenticate telegram-upload on more machines, but it is advisable to create a session file for each machine. Upload options are available in the documentation.
```

https://github.com/Nekmo/telegram-upload

In the Pypi release the file`telegram-upload.session` is in the current directory.
