### ISSUE TITLE
how to use this in python script not from CMD?

### ISSUE THREAD

**Issue by Kemal6706150033** [Nekmo/telegram-upload#75]
hi @Nekmo ,
how to use this in python script not from CMD?
can u give example please thank u so much for this work 😊

**Comment by nikotz** [comment]
i do it whit 
`subprocess.call(['Telegram-upload', '--caption'`

**Comment by Kemal6706150033** [comment]
> i do it whit
> `subprocess.call(['Telegram-upload', '--caption'`

thank u for the answer, but how print log progress bar like on CMD?
![Capture](https://user-images.githubusercontent.com/26926466/99884349-402b6380-2c60-11eb-8f1b-d9122e9d0d7e.PNG)

**Comment by Kemal6706150033** [comment]
run with subprocces is word in my local computer, then im upload and deploy to heroku and iget error like this:
![Capture](https://user-images.githubusercontent.com/26926466/99888252-01a4a180-2c7e-11eb-9461-6385e6a47908.PNG)
this is my code in bot.py
![Capture2](https://user-images.githubusercontent.com/26926466/99888258-0cf7cd00-2c7e-11eb-9072-cee46c6ee4c2.PNG)

**Comment by Nekmo** [comment]
@Kemal6706150033  You can check how it works in the file `management.py`:

https://github.com/Nekmo/telegram-upload/blob/master/telegram_upload/management.py#L50-L60

For example:

```python
from telegram_upload.client import Client
from telegram_upload.config import default_config

client = Client(default_config())
client.send_files('me', ['/path/to/file/'], delete_on_success=False, print_file_id=False,
                  force_file=False, forward=(), caption=None, no_thumbnail=False)
```

**Comment by Kemal6706150033** [comment]
thank u for answer @Nekmo 😊
but something error in my code 😣
like this :

> Traceback (most recent call last):
  File "D:\jahat.py", line 6, in <module>
    force_file=False, forward=(), caption=None, no_thumbnail=False)
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram_upload\client.py", line 84, in send_files
    progress_callback=progress, attributes=attributes)
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\sync.py", line 39, in syncified
    return loop.run_until_complete(coro)
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\uploads.py", line 374, in send_file
    supports_streaming=supports_streaming
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\uploads.py", line 686, in _file_to_media
    progress_callback=progress_callback
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\uploads.py", line 619, in upload_file
    result = await self(request)
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\users.py", line 58, in _call
    future = sender.send(request, ordered=ordered)
  File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\network\mtprotosender.py", line 168, in send
    raise ConnectionError('Cannot send requests while disconnected')
ConnectionError: Cannot send requests while disconnected
[Finished in 1.8s with exit code 1]
[shell_cmd: python -u "D:\jahat.py"]
[dir: D:\]
[path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs\;C:\Program Files (x86)\Streamlink\bin;C:\Windows\phantomjs\bin;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37;C:\Python34;C:\Python34\Scripts;C:\Python34\DLLs;C:\Program Files\gtk\bin;C:\Program Files\gtk;C:\ffmpeg\bin;C:\Windows\System32\ffmpeg\bin;C:\Program Files\Git\cmd;D:\Believe\Aplikasi\platform-tools;C:\Program Files (x86)\Bitvise SSH Client;C:\rtmpdump-2.3;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\Scripts\;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python36\;C:\Users\Kemal PC\AppData\Local\Microsoft\WindowsApps;C:\Users\Kemal PC\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PhpStorm 2019.2.2\bin;C:\Users\Kemal PC\AppData\Roaming\npm;C:\Windows\phantomjs\bin;C:\Python34;C:\Python34\Scripts;C:\Python34\DLLs;C:\Program Files\gtk\bin;C:\Program Files\gtk;C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3\bin;C:\Users\Kemal PC\AppData\Local\Programs\Fiddler;C:\ffmpeg\bin;C:\Windows\System32\ffmpeg\bin;C:\src\flutter\bin;C:\Program Files\Java\jdk1.8.0_261\bin;C:\Program Files\Java\jre1.8.0_261\bin;D:\Believe\Aplikasi\platform-tools;C:\Program Files\heroku\bin;C:\rtmpdump-2.3;]

how i fix this? im just trying delete json from .config and run the code then insert with my second account telegram and the result is same :(

**Comment by nikotz** [comment]
> run with subprocces is work in my local computer, then im upload and deploy to heroku and i get error like this:
> ![Capture](https://user-images.githubusercontent.com/26926466/99888252-01a4a180-2c7e-11eb-9461-6385e6a47908.PNG)
> this is my code in bot.py
> ![Capture2](https://user-images.githubusercontent.com/26926466/99888258-0cf7cd00-2c7e-11eb-9072-cee46c6ee4c2.PNG)

i think you have to put the path of telegram-upload is installed like "user/root/telegram-uppload"

**Comment by Nekmo** [comment]
> thank u for answer @Nekmo 
> but something error in my code 
> like this :
> 
> > Traceback (most recent call last):
> > File "D:\jahat.py", line 6, in 
> > force_file=False, forward=(), caption=None, no_thumbnail=False)
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram_upload\client.py", line 84, in send_files
> > progress_callback=progress, attributes=attributes)
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\sync.py", line 39, in syncified
> > return loop.run_until_complete(coro)
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 579, in run_until_complete
> > return future.result()
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\uploads.py", line 374, in send_file
> > supports_streaming=supports_streaming
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\uploads.py", line 686, in _file_to_media
> > progress_callback=progress_callback
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\uploads.py", line 619, in upload_file
> > result = await self(request)
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\users.py", line 30, in **call**
> > return await self._call(self._sender, request, ordered=ordered)
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\client\users.py", line 58, in _call
> > future = sender.send(request, ordered=ordered)
> > File "C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\lib\site-packages\telethon\network\mtprotosender.py", line 168, in send
> > raise ConnectionError('Cannot send requests while disconnected')
> > ConnectionError: Cannot send requests while disconnected
> > [Finished in 1.8s with exit code 1]
> > [shell_cmd: python -u "D:\jahat.py"]
> > [dir: D:]
> > [path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer\ChromaBroadcast\bin;C:\Program Files\Razer\ChromaBroadcast\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\Program Files\nodejs;C:\Program Files (x86)\Streamlink\bin;C:\Windows\phantomjs\bin;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37;C:\Python34;C:\Python34\Scripts;C:\Python34\DLLs;C:\Program Files\gtk\bin;C:\Program Files\gtk;C:\ffmpeg\bin;C:\Windows\System32\ffmpeg\bin;C:\Program Files\Git\cmd;D:\Believe\Aplikasi\platform-tools;C:\Program Files (x86)\Bitvise SSH Client;C:\rtmpdump-2.3;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37\Scripts;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python37;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python36\Scripts;C:\Users\Kemal PC\AppData\Local\Programs\Python\Python36;C:\Users\Kemal PC\AppData\Local\Microsoft\WindowsApps;C:\Users\Kemal PC\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\JetBrains\PhpStorm 2019.2.2\bin;C:\Users\Kemal PC\AppData\Roaming\npm;C:\Windows\phantomjs\bin;C:\Python34;C:\Python34\Scripts;C:\Python34\DLLs;C:\Program Files\gtk\bin;C:\Program Files\gtk;C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.3\bin;C:\Users\Kemal PC\AppData\Local\Programs\Fiddler;C:\ffmpeg\bin;C:\Windows\System32\ffmpeg\bin;C:\src\flutter\bin;C:\Program Files\Java\jdk1.8.0_261\bin;C:\Program Files\Java\jre1.8.0_261\bin;D:\Believe\Aplikasi\platform-tools;C:\Program Files\heroku\bin;C:\rtmpdump-2.3;]
> 
> how i fix this? im just trying delete json from .config and run the code then insert with my second account telegram and the result is same :(

sorry @Kemal6706150033  I had forgotten a line of code. This is the updated code:

```python
from telegram_upload.client import Client
from telegram_upload.config import default_config

client = Client(default_config())
client.start()
client.send_files('me', ['/path/to/file/'], delete_on_success=False, print_file_id=False,
                  force_file=False, forward=(), caption=None, no_thumbnail=False)
```

**Comment by Kemal6706150033** [comment]
@Nekmo its work, thank u very much 😊

**Comment by Nekmo** [comment]
You are welcome :)

**Comment by Riptide-11** [comment]
@Nekmo Sorry for commenting on closed issue but, I recently used the above code you provided, the below one 
`from telegram_upload.client import Client
from telegram_upload.config import default_config

client = Client(default_config())
client.start()
client.send_files('me', ['/path/to/file/'], delete_on_success=False, print_file_id=False,
                  force_file=False, forward=(), caption=None, no_thumbnail=False)`
In my telegram bot, but it raises a error

Error occurred - There is no current event loop in thread 'Bot:1xxxxx:worker:d217c3f2-9899-4537-a642-ebc00fbeb447_0'.

**Comment by Nekmo** [comment]
Hi @Riptide-11 you probably need this:

https://github.com/Nekmo/telegram-upload/blob/783fd6c7e8d0bd91f42095a2a1242be3d1813023/telegram_upload/client.py#L24-L25
