### ISSUE TITLE
add button

### ISSUE THREAD

**Issue by nikotz** [Nekmo/telegram-upload#76]
* telegram-upload version: 3.4
* Python version: 3
* Operating System: mac/win
* Dependencies list (run `pip freeze`):

### Description

Not an issue is more like a question, how i can send a video trow telegram upload whit a link or reaction button

**Comment by Nekmo** [comment]
@nikotz It is probably not possible from your user account. Telegram upload uses your user account (users can upload up to 2 GiB) and the buttons are used by bots (bots can upload up to 50 MiB).

**Comment by Nekmo** [comment]
Closed due to inactivity.
