### ISSUE TITLE
how to use split-files?

### ISSUE THREAD

**Issue by temporhodes** [Nekmo/telegram-upload#77]
Hi.is split files working ?

i use this method for uploading files, wnted to use split but gets an error ?
telegram-upload new.rar --large-files split 

response : 
>Usage: telegram-upload [OPTIONS] [FILES]...
Try 'telegram-upload --help' for help.
Error: no such option: --large-files

thanks.

**Comment by Nekmo** [comment]
Hi, this feature is in development branch. You can use this installing it:

```
$ pip install https://github.com/Nekmo/telegram-upload/archive/master.zip
```

https://github.com/Nekmo/telegram-upload/milestone/5
