### ISSUE TITLE
Forwarding uploaded files to a user using a bot.

### ISSUE THREAD

**Issue by cyberboysumanjay** [Nekmo/telegram-upload#8]
* telegram-upload version: 0.1.5
* Python version: 3.5
* Operating System: Elementary OS

### Description
I was wondering how do I forward the uploaded file to a user using a bot. I have the unique chat ID of the user.

Using --to @username or --to chat_id will send the uploaded file to @username from my personal Telegram ID.
### My Question
 How to send the files to a user from a Bot to a subscriber?

**Comment by Nekmo** [comment]
You need to send the files to a group. Then program a bot to forward the messages.
