### ISSUE TITLE
Wrong File_id

### ISSUE THREAD

**Issue by Liosion** [Nekmo/telegram-upload#91]
* telegram-upload version: 0.4.0
* Python version: 3.9.1
* Operating System: Windows
* Dependencies list (run `pip freeze`): All

### Description

--print-file-id Return Wrong File_id

### What I Did

Fixing it, please

**Comment by Nekmo** [comment]
I've been doing some testing and the identifier seems to be correct.

```
pack_bot_file_id(message.media)
'BAADBAADpQsAAlFnqVACU1M********'

pack_bot_file_id(message.video)
'BAADBAADpQsAAlFnqVACU1M********'


pack_bot_file_id(message.file)
None

pack_bot_file_id(message.document)
'BAADBAADpQsAAlFnqVACU1M********'
```

https://github.com/Nekmo/telegram-upload/blob/master/telegram_upload/client.py#L153

**Comment by Nekmo** [comment]
Note that this identifier is NOT related to the bots file_id. Bots have their own identifier and it is not reusable. Each bot has its own identifier for the file.

https://go-telegram-bot-api.dev/getting-started/files.html#fileid
