### ISSUE TITLE
problem with --print-file-id

### ISSUE THREAD

**Issue by Aikanairo** [Nekmo/telegram-upload#92]
* telegram-upload version: last
* Python version: 3.5
* Operating System: win 10
* Dependencies list (run `pip freeze`):

### Description

i am trying to get the file_id of the file i uploaded.

this is the command I run:

`telegram-upload film2.mp4 --print-file-id - a Name_bot`

finished uploading as file_id I get this value:

(file_id BQADBAADcAkAAsGgKVHff3RNY81X1gI)

unfortunately this id doesn't seem to be the file_id rather a unique id file

```

**Comment by Nekmo** [comment]
Please check the incidents already open. #91
